# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor1', models.FloatField(default=0)),
                ('sensor2', models.FloatField(default=0)),
            ],
        ),
    ]
