# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='sensor3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensors',
            name='sensor4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensors',
            name='sensor5',
            field=models.FloatField(default=0),
        ),
    ]
