# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_auto_20170913_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='time',
            field=models.CharField(default='Not Received', max_length=100),
        ),
    ]
