# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-05 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0003_sensors_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='sensor6',
            field=models.FloatField(default=0),
        ),
    ]
