# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-05 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0006_sensors_sensor6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='sensor6',
        ),
    ]
