# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0007_remove_sensors_sensor6'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='sensor6',
            field=models.IntegerField(default=0),
        ),
    ]
