# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0008_sensors_sensor6'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='sensor7',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensors',
            name='sensor8',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sensors',
            name='sensor9',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='sensor6',
            field=models.FloatField(default=0),
        ),
    ]
