# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-06 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0009_auto_20171006_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='serialId',
            field=models.CharField(default='Not Received', max_length=100),
        ),
    ]
