# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0010_sensors_serialid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='sensor1',
            new_name='altitude',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='sensor2',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='sensor3',
            new_name='pressure',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='sensor4',
            new_name='rainDrop',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='sensor5',
            new_name='seaPressure',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='sensor6',
            new_name='soilMoisture',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='sensor7',
            new_name='temperature',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='sensor8',
            new_name='ultrasonic',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='sensor9',
            new_name='waterLevel',
        ),
    ]
