# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0011_auto_20171101_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='soilMoisture2',
            field=models.FloatField(default=0),
        ),
    ]
